---
title: "Mapa da área de estudo"
author: "Equipe do Projeto Boto-Cinza"
date: "01/03/2022"
output:
  html_document:
    df_print: "paged"
---

```{r include=FALSE}
library(sf)
library(dplyr)
library(stringr)

pasta_proj <- rprojroot::find_rstudio_root_file()
arquivo_area <- paste0(pasta_proj, "/1_data/SHAPES_AUX/Areas_PBC.shp")
arquivo_rota <- paste0(pasta_proj, "/1_data/SHAPES_AUX/Rotas_PBC.shp")
arquivo_rota_nova <- paste0(pasta_proj, "/1_data/SHAPES_AUX/Rotas_novas_PBC.shp")
arquivo_pontos <- paste0(pasta_proj, "/1_data/SHAPES_AUX/Pontos_PBC.shp")

area_todas <- st_read(arquivo_area)
rota_todas <- st_read(arquivo_rota)
rota_novas <- st_read(arquivo_rota_nova)
pnts_todas <- st_read(arquivo_pontos)

st_crs(area_todas) <- 4674

area_L1 <- area_todas[area_todas$Linha == 1,] %>% mutate (area = c(3,2,1)) %>% arrange(area) %>% select(-Linha, -Tipo)
rotas_L1 <- rota_novas %>% mutate(km = round(as.double(st_length(geometry)/1000), 1), area = c(1,2,3)) %>% select(area, km)

area_L2 <- area_todas %>% filter(Linha == 2) %>% mutate (area = c(2,1)) %>% arrange(area) %>% select(-Linha, -Tipo)
rotas_L2 <- rota_novas %>% mutate(km = round(as.double(st_length(geometry)/1000), 1), area = c(1,2,3)) %>% filter(area != 3) %>% select(area, km)

area_L3 <- area_todas %>% filter(Linha == 3 & Tipo == "Area") %>% mutate (area = c(1,2)) %>%  select(-Linha, -Tipo)
pnts_L3 <- pnts_todas %>% filter(Linha == 3) %>% mutate(area = c(2,2,2,2,2,2,1,1,1,1,1,1,2)) %>% select(-lat, -lng, -Linha, -Area)
buffer_L3 <- area_todas %>% filter(Linha == 3 & Tipo == "Buffer") %>% mutate (area = c(1,1,1,2,2,2,2,2,2,1,1,1,2)) %>% arrange(area, as.numeric(Nome)) %>% select(-Linha, Tipo)

rotas_balsa <- rota_todas[rota_todas$Nome == "Transporte",] %>% transmute(tipo = str_sub(Id,3,3), Nome = Nome) %>%  arrange(tipo)
rotas_pesca <- rota_todas[rota_todas$Nome == "Pesca",] %>% transmute(tipo = str_sub(Id,3,3), Nome = Nome) %>% arrange(tipo)
rotas_tur_per <- rota_todas[rota_todas$Nome == "Turismo",][1,] %>% transmute(tipo = str_sub(Id,3,3), Nome = Nome) %>% arrange(tipo)
rotas_tur_mar <- rota_todas[rota_todas$Nome == "Turismo",][2,] %>% transmute(tipo = str_sub(Id,3,3), Nome = Nome) %>% arrange(tipo)
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
library(leaflet)

pal_green <- colorNumeric(palette = "Greens",
                         domain = 5:1)

pal_lines <- colorFactor(palette = "viridis",
                         domain = c("Turismo",
                                    "Transporte",
                                    "Pesca"))

leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addLayersControl(baseGroups = c("Área de Estudo 1",
                                  "Área de Estudo 2",
                                  "Área de Estudo 3",
                                  ""),
                   overlayGroups = c("Pererinha",
                                     "Marujá",
                                     "Balsa",
                                     "Pesca",
                                     "Rotas 1",
                                     "Rotas 2",
                                     "Estações de Coleta")) %>%
  hideGroup(c("Área de Estudo 1",
              "Área de Estudo 2",
              "Área de Estudo 3",
              "Rotas 1",
              "Rotas 2",
              "Estações de Coleta",
              "Pererinha",
              "Marujá",
              "Balsa",
              "Pesca")) %>%
  addScaleBar(position = "bottomleft") %>%
  addPolygons(data = area_L1, group = "Área de Estudo 1", weight = 2, color = ~pal_green(area)) %>%
  addPolygons(data = area_L2, group = "Área de Estudo 2", weight = 2, color = ~pal_green(area)) %>%
  addPolygons(data = area_L3, group = "Área de Estudo 3", weight = 2, color = ~pal_green(area)) %>%
  addPolylines(data = rotas_L1, group = "Rotas 1", weight = 2, color = ~pal_green(area)) %>%
  addPolylines(data = rotas_L2, group = "Rotas 2", weight = 2, color = ~pal_green(area)) %>%
  addPolylines(data = rotas_tur_per, group = "Pererinha", color = ~pal_lines(Nome)) %>%
  addPolylines(data = rotas_tur_mar, group = "Marujá", color = ~pal_lines(Nome)) %>%
  addPolylines(data = rotas_balsa, group = "Balsa", color = ~pal_lines(Nome)) %>%
  addPolylines(data = rotas_pesca, group = "Pesca", color = ~pal_lines(Nome)) %>%
  addCircleMarkers(data = pnts_L3, group = "Estações de Coleta", color = ~pal_green(area))


```

