---
title: "Resumo de campo"
author: "Equipe do Projeto Boto-Cinza"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(flexdashboard)
library(fontawesome)
library(dygraphs)
library(ggplot2)
library(plotly)
library(leaflet)
library(knitr)
library(timeSeries)
library(htmltools)

source("../scripts/gera_lista_pop.R")
source("../scripts/demais_func.R")

fdatabase <- gera_lista_pop(pasta_EXCEL_foto, pasta_GPS, pasta_SONDA, pasta_CAT)
fdata_sel <- filtra_fdatabase_dia("02-07-2020",fdatabase)

```


# `r fa("eye")` Visão gerão


Column {data-width=100}
-----------------------------------------------------------------------

### Número da saída
```{r}
valueBox(saida_filtrada,
         icon = "fa-code-fork")
```

### Dia da saída
```{r}
valueBox(dia_filtrado,
         icon = "fa-calendar")
```

### $\Delta$d
```{r}
valueBox(str_c(round(as.numeric(map(fdata_sel$frota$data.y, ~sum(.$dist_p_prox))),2),"km"),
         icon = "fa-map-o")
```

### $\Delta$t
```{r}
valueBox(str_c(round(as.numeric(map(fdata_sel$frota$data.y, ~sum(.$tempo_p_prox, na.rm = TRUE))),2), "h"),
         icon = "fa-clock-o")
```

### Número de grupos
```{r}
valueBox(nrow(fdata_sel$favistagens_sel),
         icon = "fa-pencil-square-o")
```


Column {data-width=300}
-----------------------------------------------------------------------

### Dados da sonda

```{r}
dygraph(as.timeSeries(data.frame(fdata_sel$fsonda_sel$data.y[[1]]))) %>% 
  dySeries("Turb", axis = "y2") %>% 
  dyHighlight(highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE,
              highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyRangeSelector() %>% 
  dyRoller(rollPeriod = 40) %>%
  dyAxis("y2", label = "Turbidez", valueRange = c(0,1000))
```


Column {data-width=200}
-----------------------------------------------------------------------

### Dados climáticos
```{r}
clima_dash <- fdata_sel$fclima_sel[, c(2,10,11,12,13,14,15,6)]
clima_dash$Hora_I <- str_sub(as.character.Date(clima_dash$datahora_I), 12, 19)
clima_dash$Vento <- str_c(clima_dash$dir_vento, " ", clima_dash$veloc_vento, " km/h")
clima_dash$Mar <- clima_dash$beaufort
clima_dash$Nuvens <- clima_dash$cobert_nuvens
clima_dash$Vis <- clima_dash$visibilidade
clima_dash$Reflexo <- clima_dash$reflexo
clima_dash$Hora_F <- str_sub(as.character.Date(clima_dash$datahora_F), 12, 19)

kable(clima_dash[,c(9:15)])
```

### Dados de deslocamento
```{r}
fdata_sel$frota_sel$data.y[[1]]$Velocidade <- 
  fdata_sel$frota_sel$data.y[[1]]$dist_p_prox / 
  as.numeric(fdata_sel$frota_sel$data.y[[1]]$tempo_p_prox)

vel_ts <- as.timeSeries(cbind(fdata_sel$frota_sel$data.y[[1]][,1],(fdata_sel$frota_sel$data.y[[1]][,6] * 0.539957)))

dy_vel_ts <- dygraph(
  smoothSupsmu(vel_ts), ylab = "Velocidade - Nós"
  ) %>%
  dyRangeSelector() %>%
  dyRoller(rollPeriod = 20) %>%
  dyHighlight()

dy_vel_ts
```

```{r include=FALSE}

vel_graph <- ts(fdata_sel$frota_sel$data.y[[1]][,6] * 0.539957)

dy_vel <- dygraph(vel_graph, xlab = "Registro", ylab = "Velocidade - Nós")

dy_vel

```


# `r fa("info-circle")` Padrões Populacionais - Informações Centrais
Column {data-width=100}
-----------------------------------------------------------------------

### Número da saída
```{r}
valueBox(saida_filtrada,
         icon = "fa-code-fork")
```

### Dia da saída
```{r}
valueBox(dia_filtrado,
         icon = "fa-calendar")
```

### $\Delta$d
```{r}
valueBox(str_c(round(as.numeric(map(fdata_sel$frota$data.y, ~sum(.$dist_p_prox))),2),"km"),
         icon = "fa-map-o")
```

### $\Delta$t
```{r}
valueBox(str_c(round(as.numeric(map(fdata_sel$frota$data.y, ~sum(.$tempo_p_prox, na.rm = TRUE))),2), "h"),
         icon = "fa-clock-o")
```

### Número de grupos
```{r}
valueBox(nrow(fdata_sel$favistagens_sel),
         icon = "fa-pencil-square-o")
```




Column {data-width=300}
-----------------------------------------------------------------------

### Mapa

```{r}
library(leaflet)

avistagens_mapa <- fdata_sel$favistagens_sel

avistagens_mapa$lab_I <- paste("<p>", avistagens_mapa$saida, " - ", avistagens_mapa$grupo, "</p>",
                               "<p>", avistagens_mapa$datahora_I, "</p>",
                               "<p>", avistagens_mapa$tam_grupo,
                                      " [m", avistagens_mapa$tam_min,
                                      " - M", avistagens_mapa$tam_max,
                                      "] c", avistagens_mapa$coesao,
                                      " e", avistagens_mapa$estado, "</p>",
                               "<p>", "n", avistagens_mapa$n_neonatos,
                                      " / i", avistagens_mapa$n_infantes,
                                      " / j", avistagens_mapa$n_juvenis,
                                      " / a", avistagens_mapa$n_adultos, "</p>",
                               "<p>", avistagens_mapa$num_fotos, "</p>"
)
                               
avistagens_mapa$lab_F <- paste("<p>", avistagens_mapa$saida, " - ", avistagens_mapa$grupo, "</p>",
                               "<p>", avistagens_mapa$datahora_F, "</p>",
                               "<p>", avistagens_mapa$tam_grupo,
                                      " [m", avistagens_mapa$tam_min,
                                      " - M", avistagens_mapa$tam_max,
                                      "] c", avistagens_mapa$coesao,
                                      " e", avistagens_mapa$estado, "</p>",
                               "<p>", "n", avistagens_mapa$n_neonatos,
                                      " / i", avistagens_mapa$n_infantes,
                                      " / j", avistagens_mapa$n_juvenis,
                                      " / a", avistagens_mapa$n_adultos, "</p>",
                               "<p>", avistagens_mapa$num_fotos, "</p>"
)

m <- leaflet() %>%
  setView(lng = -47.9,
          lat = -25,
          zoom = 11) %>%
  addProviderTiles(providers$Esri) %>%
  addPolylines( lng = fdata_sel$frota$data.y[[1]]$lng,
                lat = fdata_sel$frota$data.y[[1]]$lat) %>%
  addCircleMarkers(lng = fdata_sel$favistagens$lng_I,
                   lat = fdata_sel$favistagens$lat_I,
                   color = "green",
                   radius = 4,
                   label = lapply(avistagens_mapa$lab_I, HTML)) %>%
  addCircleMarkers(lng = fdata_sel$favistagens$lng_F,
                   lat = fdata_sel$favistagens$lat_F,
                   color = "red",
                   radius = 4,
                   label = lapply(avistagens_mapa$lab_F, HTML))

    


m
  
```

Column {data-width=200}
-----------------------------------------------------------------------

### Dados dos grupo

```{r}
avistagens_dash <- fdata_sel$favistagens_sel

avistagens_dash$Hora_I <- str_sub(as.character.Date(fdata_sel$favistagens_sel$datahora_I), 12, 19)
avistagens_dash$Hora_F <- str_sub(as.character.Date(fdata_sel$favistagens_sel$datahora_F), 12, 19)
avistagens_dash$Estado <- avistagens_dash$estado
avistagens_dash$Coesao <- avistagens_dash$coesao
avistagens_dash$"Tam(est)" <- str_c(avistagens_dash$tam_grupo, " ( ", avistagens_dash$tam_min, " - ", avistagens_dash$tam_max, ")", sep = "")
avistagens_dash$"N / I / J / A" <- str_c(avistagens_dash$n_neonatos,
                                    " / ", avistagens_dash$n_infantes,
                                    " / ", avistagens_dash$n_juvenis,
                                    " / ", avistagens_dash$n_adultos)
kable(avistagens_dash[,c(23,25:28,24)])

```

