---
title: "Resumo de campo"
author: "Equipe do Projeto Boto-Cinza"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r echo=FALSE}
library(lubridate)
library(readxl)
library(stringr)
library(fontawesome)
library(knitr)
library(kableExtra)
library(tuicalendr)
library(leaflet)
library(rgdal)
library(tuneR)
```

```{r echo=FALSE}
inicio_relatorio <- dmy("09/07/2020")

fim_relatorio <- dmy("08/11/2020")

pasta_L1 <- "C:/Users/PBC-PESQUISA/Documents/PROJETO BOTO-CINZA/PESQUISA/LINHA_1"
pasta_L2 <- "C:/Users/PBC-PESQUISA/Documents/PROJETO BOTO-CINZA/PESQUISA/LINHA_2"
pasta_L3 <- "C:/Users/PBC-PESQUISA/Documents/PROJETO BOTO-CINZA/PESQUISA/LINHA_3"

```


# Período: `r inicio_relatorio` --- `r fim_relatorio`

Column {data-width=250}
-----------------------------------------------------------------------

### Padrões Populacionais

```{r echo=FALSE}
source("scripts/controle_L1.R")

td1 <- controle_L1(pasta_L1)

td1[1:8] %>%
  kable(escape = FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "striped"), full_width = FALSE, position = "right") %>%
  row_spec(0, angle = -45, bold = TRUE, align = "center")

```

### Ecologia Comportamental 

```{r echo=FALSE}
source("scripts/controle_L2.R")

td2 <- controle_L2(pasta_L2)

td2[1:7] %>%
  kable(escape = FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "striped"), full_width = FALSE, position = "right") %>%
  row_spec(0, angle = -45, bold = TRUE, align = "center")
```

### Ecologia Acústica

```{r echo=FALSE}
source("scripts/controle_L3.R")

td3 <- controle_L3(pasta_L3)

td3[1:8] %>%
  kable(escape = FALSE) %>%
  kable_styling(bootstrap_options = c("hover", "striped"), full_width = FALSE, position = "right") %>%
  row_spec(0, angle = -45, bold = TRUE, align = "center")
```

Column {data-width=300 .tabset}
-----------------------------------------------------------------------


### Calendário 

```{r echo=FALSE}

cal <- calendar(defaultView = "month", useNav = TRUE, height = 100) %>% 
  
  set_calendars_props(id = "L1_campo", name = "Campos de Padrões Populacionais", color = "#FFF", bgColor = "#DC143C") %>%
  set_calendars_props(id = "L1_prazo", name = "Pós-Campo de Padrões Populacionais", color = "#FFF", bgColor = "#FFC0CB") %>%
  
  set_calendars_props(id = "L2_campo", name = "Campos de Ecologia Comportamental", color = "#FFF", bgColor = "#0000CD") %>%
  set_calendars_props(id = "L2_prazo", name = "Pós-Campos de Ecologia Comportamental", color = "#FFF", bgColor = "#ADD8E6") %>%
  
  set_calendars_props(id = "L3_campo", name = "Campos de Ecologia Acústica", color = "#FFF", bgColor = "#32CD32") %>%
  set_calendars_props(id = "L3_prazo", name = "Pós-Campos de Ecologia Acústica", color = "#FFF", bgColor = "#98FB98")

for (i in 1:length(td1$DATA)) {
  cal <- cal %>%
    
    add_schedule(
      start = td1$DATA[i],
      end = td1$DATA[i],
      title = paste("Linha 1 - Campo", td1$SAIDA[i], sep = ""),
      category = "allday",
      calendarId = "L1_campo") %>%
    
    add_schedule(
      start = td1$DATA[i] + days(10),
      end = td1$DATA[i] + days(10),
      title = paste("Linha 1 - Pós-Campo", td1$SAIDA[i], sep = ""),
      category = "allday",
      calendarId = "L1_prazo")
}

for (i in 1:length(td2$DATA)) {
  cal <- cal %>%
    add_schedule(
    start = td2$DATA[i],
    end = td2$DATA[i],
    title = paste("Linha 2 - Campo", td2$SAIDA[i], sep = ""),
    category = "allday",
    calendarId = "L2_campo") %>%
    
    add_schedule(
      start = td2$DATA[i] + days(10),
      end = td2$DATA[i] + days(10),
      title = paste("Linha 2 - Pós-Campo", td2$EXP[i], sep = ""),
      category = "allday",
      calendarId = "L2_prazo")
}

for (i in 1:length(td3$DATA)) {
  cal <- cal %>%
    add_schedule(
    start = td3$DATA[i],
    end = td3$DATA[i],
    title = paste("Linha 3 - Campo", td3$SAIDA[i], sep = ""),
    category = "allday",
    calendarId = "L3_campo") %>%
    
    add_schedule(
      start = td3$DATA[i] + days(10),
      end = td3$DATA[i] + days(10),
      title = paste("Linha 3 - Pós-Campo", td3$EXP[i], sep = ""),
      category = "allday",
      calendarId = "L3_prazo")
}


 
cal  
```

### `r fa("fas fa-info-circle")` Para Relatório {data-height=150}

#### Padrões Populacionais
```{r echo=FALSE}
source("scripts/bd_L1.R")

bd_L1 <- bd_L1(pasta_L1)


kable(bd_L1$saidas[17:24]) %>%
  kable_styling(bootstrap_options = c("hover", "striped"), position = "center")

```

#### Ecologia Comportamental
```{r echo=FALSE}
source("scripts/bd_L2.R")

bd_L2 <- bd_L2(pasta_L2)


kable(bd_L2$saidas[17:24]) %>%
  kable_styling(bootstrap_options = c("hover", "striped"), position = "center")

```

#### Ecologia Acústica
```{r echo=FALSE}
source("scripts/bd_L3.R")

bd_L3 <- bd_L3(pasta_L3)


kable(bd_L3$saidas[17:23]) %>%
  kable_styling(bootstrap_options = c("hover", "striped"), position = "center")

```



Column {data-width=450}
-----------------------------------------------------------------------

### Mapa {data-height=350}

```{r echo=FALSE}
source("scripts/le_rota_L.R")

rotas_L1 <- le_rota_L(pasta_L1)
rotas_L2 <- le_rota_L(pasta_L2)
rotas_L3 <- le_rota_L(pasta_L3)

mapa <- leaflet() %>%
  setView(lng = -47.9, lat = -25, zoom = 11) %>%
  addProviderTiles(provider = providers$CartoDB.Positron, group = "Base")

rotulos_L1 <- NULL
rotulos_L2 <- NULL
rotulos_L3 <- NULL

for (i in 1:nrow(rotas_L1)) {
  
  data <- readOGR(rotas_L1$arquivos_rota[[i]], layer = "tracks", verbose = FALSE)
  
  rotulos_L1[[i]] <- paste("Linha 1 - ", as.character(rotas_L1$data_rota[[i]]), sep = "")
  
  mapa <- addPolylines(mapa,
                       data = data,
                       group = rotulos_L1[[i]],
                       weight = 2,
                       color = "red",
                       smoothFactor = 3)
}


for (i in 1:nrow(rotas_L2)) {
  
  data <- readOGR(rotas_L2$arquivos_rota[[i]], layer = "tracks", verbose = FALSE)

  rotulos_L2[[i]] <- paste("Linha 2 - ", as.character(rotas_L2$data_rota[[i]]), sep = "")

  mapa <- addPolylines(mapa,
                       data = data,
                       group = rotulos_L2[[i]],
                       weight = 2,
                       color = "blue",
                       smoothFactor = 3)
}


for (i in 1:nrow(rotas_L3)) {
  
  data <- readOGR(rotas_L3$arquivos_rota[[i]], layer = "tracks", verbose = FALSE)
  
  rotulos_L3[[i]] <- paste("Linha 3 - ", as.character(rotas_L3$data_rota[[i]]), sep = "")

  mapa <- addPolylines(mapa,
                       data = data,
                       group = rotulos_L3[[i]],
                       weight = 2,
                       color = "green",
                       smoothFactor = 3)
}

mapa <- addLayersControl(mapa, position = "topright", baseGroups = "Base", overlayGroups = c(rotulos_L1, rotulos_L2, rotulos_L3), options = layersControlOptions(collapsed = FALSE))

mapa

```

